name: D-ops Daily/Weekly Report
on:
   schedule:
      # 매일 오후 10시 (UTC+9 기준)
      - cron: '0 13 * * *'
      # 매주 월요일 오전 10시 (UTC+9 기준) - 이전 주 리포트
      - cron: '0 1 * * 1'
   # 수동 실행을 위한 워크플로우 디스패치 추가
   workflow_dispatch:
      inputs:
         report_type:
            description: '리포트 종류'
            required: true
            default: 'daily'
            type: choice
            options:
               - daily
               - weekly

jobs:
   send-report:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3

         - name: Setup Node.js
           uses: actions/setup-node@v3
           with:
              node-version: '18'
              cache: 'npm'

         - name: Install dependencies
           run: npm install

         - name: Generate and send report
           env:
              SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
              SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
              SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              REPORT_TYPE: ${{ github.event.inputs.report_type || github.event.schedule == '0 1 * * 1' && 'weekly' || 'daily' }}
           run: node scripts/report.js
