name: D-ops Daily/Weekly Report
on:
   schedule:
      # 매일 오후 6시 (UTC+9 기준)
      - cron: '0 9 * * *'
   # 수동 실행을 위한 워크플로우 디스패치 추가
   workflow_dispatch:

jobs:
   send-report:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3

         - name: Setup Node.js
           uses: actions/setup-node@v3
           with:
              node-version: '18'
              cache: 'npm'

         - name: Install dependencies
           run: npm install

         - name: Generate and send report
           env:
              SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
              SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
              SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
           run: node scripts/report.js
